### PR TITLE
Add Catalan language and update Spanish language

### PR DESCRIPTION
**Pull request by deividgp**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=2050) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=2050) before we can accept your contribution.<br/><br/>:x: deividgp [sign now](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=2050)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/FluentValidation/FluentValidation?pullRequest=2050) it.</sub>

**Comment by JeremySkinner** [comment]
Hi @deividgp thanks for this. The tests are currently failing as the new language hasn't been added to the LanguageManager. Please could you add it in there too? https://github.com/FluentValidation/FluentValidation/blob/aee69fef62bc73f89a192c7ecc7b40b2ede21cf2/src/FluentValidation/Resources/LanguageManager.cs#L39

Thanks!

**Comment by deividgp** [comment]
oops, did not notice that file. It should work now @JeremySkinner .

**Comment by JeremySkinner** [comment]
Merged, thanks!

**Comment by alebrozzo** [comment]
I believe the intended Spanish translation fix is incorrect. The plural for "carácter" is "caracteres", without a tilde.

ref: [RAE article](https://www.rae.es/dpd/car%C3%A1cter)

RAE, or Real Academia Española ([Spanish Royal Academy](https://en.wikipedia.org/wiki/Royal_Spanish_Academy)) is the oficial Spanish language institution

**Pull request merged**
