### PR TITLE
Support indexers in property chain expressions.

### PR DESCRIPTION
**Pull request by JeremySkinner**
This is to support #1339

### CODE REVIEW

**Comment by Luke-TE** [comment]
Hi, 
is there a reason WHY this was closed without being merged?
Thanks

**Comment by JeremySkinner** [comment]
I decided against implementing it as the issue is an uncommon edge case, and I didn't like the solution and don't want to maintain it.

**Comment by Luke-TE** [comment]
I see. That's unfortunate, I just ran into that edge case :/

**Comment by JeremySkinner** [comment]
Use the string-based overloads in the test helper rather than the lambda overloads if you need indexers.

**Comment by Luke-TE** [comment]
Thanks, that works great!
I originally tried it with the `validator.ShouldHaveValidationErrorFor(...)` style but it seems to only be supported for the `result.ShouldHaveValidationErrorFor(...)` style.

**Comment by JeremySkinner** [comment]
Yes, the `result.ShouldHaveValidationErrorFor` style is the way to go. The old versions will be deprecated in the next release

**Pull request closed without merging**
