### PR TITLE
Update LanguageManager.cs with SlovenianLanguage

### PR DESCRIPTION
**Pull request by bostjankosi**

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Thanks for combining the PRs - I'll aim to get this merged in tomorrow or Friday.

**Comment by JeremySkinner** [comment]
@bostjankosi I don't really understand your question - does the [IStringLocalizer](https://docs.fluentvalidation.net/en/latest/localization.html#istringlocalizer) help? If you have further questions could you open a separate issue? Thanks.

**Comment by bostjankosi** [comment]
Thanks Jeremy

When / how would be new version with Slovenian language available.


Lep pozdrav / Best regards / Mit freundlichen Grüßen
---------------------------
Boštjan Kosi

00386 (0)40 537 819
Skype name: bostjankosi
www.kvint.si<http://www.kvint.si/> | www.trace.si<http://www.trace.si/> www.trace-solutions.eu<http://www.trace-solutions.eu/>

Kvint d.o.o.
Brilejeva 6, SI-1000 Ljubljana, Slovenija
Poslovalnica/Branch office Ormož: tel.:  00386 (0)2 741 17 61, Kolodvorska cesta 6, SI-2270 Ormož, Slovenija

To elektronsko sporočilo in vse morebitne priloge so last podjetja Kvint d.o.o. in so poslovna skrivnost, ki je namenjene izključno naslovniku.
Če ste sporočilo prejeli pomotoma, Vas prosimo, da obvestite pošiljatelja in sporočilo takoj uničite.
Prav tako je izrecno prepovedano kakršnokoli razkritje, distribucija ali kopiranje vsebine sporočila. Elektronsko sporočilo je pregledano z antivirusnim programom.
This e-mail may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.
Any unauthorized use, copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Trace.Solutions je registrirana blagovna znamka podjetja Kvint d.o.o.
Trace.Solutions is a registered trademark of Kvint d.o.o.

**Comment by JeremySkinner** [comment]
It'll be part of the 9.0 release, which will be in the next couple of months.

**Comment by bostjankosi** [comment]
Oh.
Wow could i use slovenian language before ? What a night build or the other way?
This is very important for our project.

Lep pozdrav / Best regards / Mit freundlichen Grüßen
---------------------------
Boštjan Kosi

00386 (0)40 537 819
Skype name: bostjankosi
www.kvint.si<http://www.kvint.si/> | www.trace.si<http://www.trace.si/> www.trace-solutions.eu<http://www.trace-solutions.eu/>

Kvint d.o.o.
Brilejeva 6, SI-1000 Ljubljana, Slovenija
Poslovalnica/Branch office Ormož: tel.:  00386 (0)2 741 17 61, Kolodvorska cesta 6, SI-2270 Ormož, Slovenija

To elektronsko sporočilo in vse morebitne priloge so last podjetja Kvint d.o.o. in so poslovna skrivnost, ki je namenjene izključno naslovniku.
Če ste sporočilo prejeli pomotoma, Vas prosimo, da obvestite pošiljatelja in sporočilo takoj uničite.
Prav tako je izrecno prepovedano kakršnokoli razkritje, distribucija ali kopiranje vsebine sporočila. Elektronsko sporočilo je pregledano z antivirusnim programom.
This e-mail may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.
Any unauthorized use, copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Trace.Solutions je registrirana blagovna znamka podjetja Kvint d.o.o.
Trace.Solutions is a registered trademark of Kvint d.o.o.

**Comment by JeremySkinner** [comment]
I understand that it's important to you, but please keep in mind that I work on this project in my spare time, for free, so I can't always get things done immediately. 

I can try and put out a preview release sooner - I might be able to do that tomorrow or over the weekend, but I can't guarantee it.

If that's not fast enough for you, [then you'll need to include the messages in your own project](https://docs.fluentvalidation.net/en/latest/localization.html#default-messages).

Thanks for your patience.

**Comment by bostjankosi** [comment]
Thank Jeremy.

I can wait one week. No problem.

Lep pozdrav / Best regards / Mit freundlichen Grüßen
---------------------------
Boštjan Kosi

00386 (0)40 537 819
Skype name: bostjankosi
www.kvint.si<http://www.kvint.si/> | www.trace.si<http://www.trace.si/> www.trace-solutions.eu<http://www.trace-solutions.eu/>

Kvint d.o.o.
Brilejeva 6, SI-1000 Ljubljana, Slovenija
Poslovalnica/Branch office Ormož: tel.:  00386 (0)2 741 17 61, Kolodvorska cesta 6, SI-2270 Ormož, Slovenija

To elektronsko sporočilo in vse morebitne priloge so last podjetja Kvint d.o.o. in so poslovna skrivnost, ki je namenjene izključno naslovniku.
Če ste sporočilo prejeli pomotoma, Vas prosimo, da obvestite pošiljatelja in sporočilo takoj uničite.
Prav tako je izrecno prepovedano kakršnokoli razkritje, distribucija ali kopiranje vsebine sporočila. Elektronsko sporočilo je pregledano z antivirusnim programom.
This e-mail may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.
Any unauthorized use, copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Trace.Solutions je registrirana blagovna znamka podjetja Kvint d.o.o.
Trace.Solutions is a registered trademark of Kvint d.o.o.

**Comment by JeremySkinner** [comment]
@bostjankosi I've pushed out 9.0-preview2 to nuget which includes the Slovenian translations. Please feel free to give it a try. 

Note that 9.0 is not fully finished yet (I'm aiming for at least 1 more preview before release). Please see the upgrade guide at https://docs.fluentvalidation.net/en/latest/upgrading-to-9.html as 9.0 does contain some breaking changes. 

If you run into any problems, please let me know by opening a new issue.

Thanks!

**Comment by bostjankosi** [comment]
Jeremy…thanks.

Lep pozdrav / Best regards / Mit freundlichen Grüßen
---------------------------
Boštjan Kosi

**Pull request merged**
