### PR TITLE
Avoid expensive calls to Enum.GetNames() when validating string exists in enum names

### PR DESCRIPTION
**Pull request by tedvanderveen**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1595) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1595) before we can accept your contribution.<br/><br/>:x: tedvanderveen [sign now](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1595)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/FluentValidation/FluentValidation?pullRequest=1595) it.</sub>

**Comment by JeremySkinner** [comment]
@tedvanderveen Did you not want this included anymore? I was going to try and review it later in the week

**Comment by tedvanderveen** [comment]
@JeremySkinner I ran some additional tests and found the performance gain was not really worth it. We are using FluentValidation on a system that triggers validation 1,000+ times per second. I resorted to using [FastEnum](https://github.com/xin9le/FastEnum) in a custom validator to minimize the impact of enum member validation:

```
.Custom((country, context) =>
{
    if (string.IsNullOrEmpty(country) == false && (country.Length != 2 || FastEnum.IsDefined<ISO3166Countries>(country) == false))
    {
        context.AddFailure("not a valid ISO 3166-1 alpha-2 country code");
    }
});
```
If you're interested, we could include the FastEnum NuGet package or merge their code implementations into FluentValidation. I'd be happy to re-submit my PR in that case.

**Comment by JeremySkinner** [comment]
Thanks for the update, glad you have a working solution. No I don't think there's a need to bring FastEnum into FluentValidation - better to leave that separate and allow users to explicitly make use of it if they want to. Thanks for wanting to be involved!

**Pull request closed without merging**
