### PR TITLE
Throw exception on ValidateAndThrow even if PreValidate prevents further Validation

### PR DESCRIPTION
**Pull request by matthiaslischka**
My attempt at fixing issue #1736.

BR Matthias

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1737) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1737) before we can accept your contribution.<br/><br/>:x: matthiaslischka [sign now](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1737)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/FluentValidation/FluentValidation?pullRequest=1737) it.</sub>

**Comment by JeremySkinner** [comment]
Thanks, that looks like a good solution. I’ve just moved house so won’t be able to do a new release straight away but will try to get to it soon.

**Comment by matthiaslischka** [comment]
No hurry. I already worked around that for now. Thx for the feedback.

**Comment by JeremySkinner** [comment]
Hi @matthiaslischka this doesn't work correctly at the moment and will need some work before it can be merged. 


1. Firstly, the condition needs to check `!result.IsValid` too - at the moment the exception will be thrown if PreValidate returns false, regardless of whether any failures were actually generated. 
2. We'll need tests to cover the above scenario - when PreValidate returns false, but no failures are generated, no exception should be thrown
3. The new logic is missing from `ValidateAsync`, meaning sync & async validation will behave differently. The same logic needs to be added to `ValidateAsync`. 
4. Tests for the async behaviour will need to be added (for every test for `ValidateAndThrow` there needs to be equivalent async tests that exercise `ValidateAndThrowAsync`

If you could make these changes then I'll get this merged.

**Comment by matthiaslischka** [comment]
@JeremySkinner Terribly sorry for the poor quality. Have to admit, it was done in a hurry.

**Comment by JeremySkinner** [comment]
No worries, I’ll try and give this another review over the weekend and then get it merged. Thanks!

**Comment by JeremySkinner** [comment]
Thanks, this looks good. I made a couple of changes to your async tests. By making the methods async and using `Assert.ThrowsAsync` you don't need to worry about extracting AggregateExceptions. Eg:

Before:
```csharp
public void Throws_exception_when_preValidate_fails_and_continueValidation_true_async() {
	var validator = new TestValidatorWithPreValidate {
		PreValidateMethod = (context, result) => {
			result.Errors.Add(new ValidationFailure("test", "test"));
			return true;
		}
	};

	typeof(ValidationException).ShouldBeThrownBy(() => {
		try {
			validator.ValidateAndThrowAsync(new Person()).Wait();
		}
		catch (AggregateException agrEx) {
			throw agrEx.InnerException;
		}
	});
}

```

After:
```csharp
[Fact]
public async Task Throws_exception_when_preValidate_fails_and_continueValidation_true_async() {
	var validator = new TestValidatorWithPreValidate {
		PreValidateMethod = (context, result) => {
			result.Errors.Add(new ValidationFailure("test", "test"));
			return true;
		}
	};

	await Assert.ThrowsAsync<ValidationException>(async () => {
			await validator.ValidateAndThrowAsync(new Person());
	});
}

```

**Comment by matthiaslischka** [comment]
I only did it like that because it was already done like that in some tests above. I was wondering why but wanted to stay consistent. ^^
Thx for the merge. :)

**Comment by JeremySkinner** [comment]
I think it was probably just legacy! I’ve updated the other tests in that file too

**Pull request merged**
