### PR TITLE
Fix scale precision error message when digits is calculated as negative

### PR DESCRIPTION
**Pull request by SatsunkevichAlex**
a possible way to fix wrong scale precision error message

#1791

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1790) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1790) before we can accept your contribution.<br/><br/>:x: SatsunkevichAlex [sign now](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1790)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/FluentValidation/FluentValidation?pullRequest=1790) it.</sub>

**Comment by JeremySkinner** [comment]
Hi @SatsunkevichAlex thanks for this. I think that rather assigning scale to precision, it'd be clearer if the modification was done at the point where the message argument is appended, so it would become:

```csharp
.AppendArgument("Digits", actualIntegerDigits < 0 ? 0 : actualIntegerDigits)

```

I think this is a bit clearer than assigning the scale variable to the precision variable. If you could make that change then I'll get this merged in for the next release. Thanks!

**Comment by SatsunkevichAlex** [comment]
Applied your recommendation

**Comment by JeremySkinner** [comment]
Thanks, I'll aim to get this in over the weekend.

**Comment by JeremySkinner** [comment]
Merged, thanks

**Pull request merged**
