### PR TITLE
Fix null debuggability

### PR DESCRIPTION
**Pull request by MeikelLP**
see #2152 

Please squash when merging :)

### CODE REVIEW

**Comment by MeikelLP** [comment]
@dotnet-policy-service agree company="Konzept & Marketing GmbH"

**Comment by JeremySkinner** [comment]
Thanks for this. A few comments:

- The try/catch logic should will need to be duplicated inside `CollectionPropertyRule` too
  - Will also need tests for handling collection rules (RuleForEach) 
- The exception type being thrown isn't correct - it should throw another NullReferenceException (not a ValidationException, which is only used for validation failures) which wraps the original, something like this:

```csharp
catch (NullReferenceException nre) {
  throw new NullReferenceException($"NullReferenceException occurred when executing rule for {context.PropertyPath}. If this property can be null you should add a null check using a When condition", nre);
}

```

**Comment by MeikelLP** [comment]
I never really worked with `RuleForEach` but I tried my best :)

**Comment by JeremySkinner** [comment]
That's great, thanks. Could you update the message in the exception thrown to be the one I suggested too? Once that's done I'll do a bit of extra testing and then should be able to get it merged.

**Comment by MeikelLP** [comment]
done

**Comment by JeremySkinner** [comment]
The logic and tests for RuleForEach wasn't correct - the catch was in the wrong place, it was catching collections thrown inside the property validator, not exceptions thrown by the rule definition. I've corrected this, and also done some additional cleanup. Merged for the 11.9 release.

**Pull request merged**
