### PR TITLE
Move the IValidationRule<T, TProperty>.SetDisplayName(string) method to the IValidationRule interface.

### PR DESCRIPTION
**Pull request by hogwartsdeveloper**
issues #2179

### CODE REVIEW

**Comment by hogwartsdeveloper** [comment]
@dotnet-policy-service agree

**Review by JeremySkinner — CHANGES_REQUESTED** [review]
hi @hogwartsdeveloper this is targetting the wrong branch. This change is scheduled for the 12.0 release, so needs to target the `12.x-dev` branch.

**Comment by JeremySkinner** [comment]
hi @hogwartsdeveloper you need to rebase onto the 12.x-dev branch, changing the branch for the PR isn't enough to do this

**Comment by hogwartsdeveloper** [comment]
> hi @hogwartsdeveloper you need to rebase onto the 12.x-dev branch, changing the branch for the PR doesn't do this automatically.

ready)

**Comment by JeremySkinner** [comment]
thanks!

**Pull request merged**
