### PR TITLE
Fix the issue that the ChildRules will corrupt the RuleSets of a validator passed to the SetValidator

### PR DESCRIPTION
**Pull request by sumtec**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1982) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1982) before we can accept your contribution.<br/><br/>:x: sumtec [sign now](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1982)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/FluentValidation/FluentValidation?pullRequest=1982) it.</sub>

**Review by JeremySkinner — CHANGES_REQUESTED** [review]
Hi @sumtec thanks for this. It looks like the new test is currently failing - could you take a look at that please? 

```
  Failed FluentValidation.Tests.ChildRulesTests.ChildRules_works_with_SetValidator_and_RuleSet [3 ms]
  Error Message:
   Assert.Equal() Failure
Expected: 1
Actual:   2
  Stack Trace:
     at FluentValidation.Tests.TestExtensions.ShouldEqual(Object actual, Object expected) in /home/runner/work/FluentValidation/FluentValidation/src/FluentValidation.Tests/TestExtensions.cs:line 27
   at FluentValidation.Tests.ChildRulesTests.ChildRules_works_with_SetValidator_and_RuleSet() in /home/runner/work/FluentValidation/FluentValidation/src/FluentValidation.Tests/ChildRulesTests.cs:line 83
```

**Comment by sumtec** [comment]
> Hi @sumtec thanks for this. It looks like the new test is currently failing - could you take a look at that please? It looks like everything in ruleset `b` is still being executed, even though only `a` is selected for inclusion.
> 
> ```
>   Failed FluentValidation.Tests.ChildRulesTests.ChildRules_works_with_SetValidator_and_RuleSet [3 ms]
>   Error Message:
>    Assert.Equal() Failure
> Expected: 1
> Actual:   2
>   Stack Trace:
>      at FluentValidation.Tests.TestExtensions.ShouldEqual(Object actual, Object expected) in /home/runner/work/FluentValidation/FluentValidation/src/FluentValidation.Tests/TestExtensions.cs:line 27
>    at FluentValidation.Tests.ChildRulesTests.ChildRules_works_with_SetValidator_and_RuleSet() in /home/runner/work/FluentValidation/FluentValidation/src/FluentValidation.Tests/ChildRulesTests.cs:line 83
> ```

Sorry that the last check-in seems to have some issues. Neither the test case nor the source code is the correct one.
I've made a new commit to fix the files.

**Comment by JeremySkinner** [comment]
Thanks! I'll aim to get a release out over the weekend.

**Review by JeremySkinner — APPROVED** [review]

**Pull request merged**
