### PR TITLE
fixed broken URLs

### PR DESCRIPTION
**Pull request by janschreier**
fixed all links that had a wrong / 

(sorry the global.json bit is still included - I guess I should do my git course now...)

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Are you able to rebase this, as it has conflicts?

**Comment by janschreier** [comment]
ok, will do, but give some time (I thought that rebase would be part of the answer, but having never really worked with Git, I have to figure out how to do this)

**Comment by JeremySkinner** [comment]
Ok no problem, leave it to me I'll sort it.

**Comment by JeremySkinner** [comment]
I've rebased your fork so it has a linear history without a merge commit, so this will apply cleanly now.

**Pull request merged**
