### PR TITLE
Add new extension point for registering FluentValidation's aspnet integration

### PR DESCRIPTION
**Pull request by Sherif-Ahmed**
Add a new extension point to add fluent validation services (#1726)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1727) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1727) before we can accept your contribution.<br/><br/>:x: Sherif-Ahmed [sign now](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1727)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/FluentValidation/FluentValidation?pullRequest=1727) it.</sub>

**Comment by JeremySkinner** [comment]
Merged, thanks

**Comment by Sherif-Ahmed** [comment]
Hello, 

When version 10.2 will be released?

**Comment by JeremySkinner** [comment]
No eta at the moment. I’ve just moved house so my current focus is on building furniture and unpacking.

**Comment by Sherif-Ahmed** [comment]
Good luck

**Pull request merged**
