### PR TITLE
Update NorwegianBokmalLanguage.cs

### PR DESCRIPTION
**Pull request by stefanhaug**
EmailValidator incorrectly uses PropertyName.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1766) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1766) before we can accept your contribution.<br/><br/>:x: stefanhaug [sign now](https://cla.dotnetfoundation.org/FluentValidation/FluentValidation?pullRequest=1766)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/FluentValidation/FluentValidation?pullRequest=1766) it.</sub>

**Comment by JeremySkinner** [comment]
Hi, this is actually correct - the error messages across all languages for the email validator use PropetyName, saying that “the value of <property name> is not an email address”.

This isn’t something we’ll change in the library but if you’d prefer to use the property value in the message you can override the message, although if you do this then the message won’t work with client-side validation in asp.net, which can’t use the PropertyValue placeholder.

**Comment by stefanhaug** [comment]
Ok,

But the text "'{PropertyName}' er ikke en gyldig e-postadresse." in english equals something in the lines of "'{PropertyName}' is not a valid e-mail address.", which for me seems wrong.

**Comment by JeremySkinner** [comment]
hi, it’s intentional: https://github.com/FluentValidation/FluentValidation/blob/4239cf4c71aecde1ccf8a9ca8e695955facc01bf/src/FluentValidation/Resources/Languages/EnglishLanguage.cs#L31

**Pull request closed without merging**
