### PR TITLE
Issues #2124 Make TryGetPropertyValue generic to avoid boxing

### PR DESCRIPTION
**Pull request by hogwartsdeveloper**
#2124 TryGetPropertyValue generic to avoid boxing

### CODE REVIEW

**Comment by JeremySkinner** [comment]
hi @hogwartsdeveloperthis also needs rebasing onto the 12.x-dev branch.

**Comment by hogwartsdeveloper** [comment]
> hi @hogwartsdeveloper this also needs rebasing onto the 12.x-dev branch (changing target branch for the PR doesn't do this automatically)

ready)

**Comment by JeremySkinner** [comment]
thanks!

**Comment by hogwartsdeveloper** [comment]
> thanks!

Do I need to write tests for the method?

**Comment by JeremySkinner** [comment]
If you can that'd be great, otherwise I'll add them when I get some time

**Pull request merged**
