### PR TITLE
enable nullable in FluentValidation.DependencyInjectionExtensions

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Thanks for the suggestion but I'm not keen on the nullable feature so won't be including this

**Comment by SimonCropp** [comment]
interesting. any reasoning so i can get more understanding of your perspective?

**Comment by JeremySkinner** [comment]
Sure,

- I don't like the 'virality' of nullable, how it tends to cascade throughout a codebase as you start introducing it 
- I don't like how it introduces dual meaning of the `?` operator (ie how it means something different in the context of nullable value types vs nullable reference types) 

It's just a personal preference really

**Comment by SimonCropp** [comment]
fair enough

**Pull request closed without merging**
